### ISSUE TITLE
Integration with Home Assistant To-Do?

### ISSUE THREAD

**Issue by saya6k** [Anrolosia/Shopping-List-with-Grocy#31] opened 2023-10-26 00:57 UTC
Hi,
in Home Assistant 2023.11.0 RC, now Home Assistant have To-Do as own integration, and support integrating external to-do with Home-Assistant like Todoist.
Will this integration also support integration with Home Assistant To-Do?

**Comment by Anrolosia** [comment] 2023-10-26 11:49
Hey @saya6k !

I just saw the changelog for 2023.11.0 RC, and it looks great! Indeed, it could be a great idea!

I will have to investigate how to integrate properly with TODOs and shopping lists, but yeah, could be great!

Thank you

**Comment by Anrolosia** [comment] 2023-11-04 19:23
I will close this ticket, because I will not integrate this integration with HomeAssistant To-Do, there is no quantity in there, it's just a To-Do list. If one day they will integrate the quantity aspect, I will reconsider that :)

**Closed by Anrolosia** 2023-11-04 19:23 UTC
Labels: enhancement

**Comment by saya6k** [comment] 2024-01-11 16:38
Now Home Assistant Todo domain have description. And I think it may used as quantity like this:

<img width="512" alt="스크린샷 2024-01-12 01 38 28" src="https://github.com/Anrolosia/Shopping-List-with-Grocy/assets/63517312/1be0db8c-d070-479f-8930-7af45d8e1203">

**Comment by Anrolosia** [comment] 2024-01-17 13:49
Well, the issue is not just about quantities, I took a look at that integration, and it seems there is no way to add a unique ID on each item, if you want to remove something from the list, you have to do it through the name of the item, which represents a bad way / challenge to deal with the shopping list (add, remove, update items)
I will continue to check on how that will evolve, but right now, it's still not a good idea :(
